import { AppLanguageTexts } from "../../const/languageTexts";

export const loadFfxivNeededData = () => {
  let LANGUAGE_TEXTS = AppLanguageTexts();
  const ALL_PLAYER_JOBS: string[] = [
    LANGUAGE_TEXTS.PLD_EN_NAME,
    LANGUAGE_TEXTS.WAR_EN_NAME,
    LANGUAGE_TEXTS.DRK_EN_NAME,
    LANGUAGE_TEXTS.GNB_EN_NAME,
    LANGUAGE_TEXTS.WHM_EN_NAME,
    LANGUAGE_TEXTS.SCH_EN_NAME,
    LANGUAGE_TEXTS.AST_EN_NAME,
    LANGUAGE_TEXTS.SGE_EN_NAME,
    LANGUAGE_TEXTS.DRG_EN_NAME,
    LANGUAGE_TEXTS.MNK_EN_NAME,
    LANGUAGE_TEXTS.NIN_EN_NAME,
    LANGUAGE_TEXTS.SAM_EN_NAME,
    LANGUAGE_TEXTS.RPR_EN_NAME,
    LANGUAGE_TEXTS.VPR_EN_NAME,
    LANGUAGE_TEXTS.BRD_EN_NAME,
    LANGUAGE_TEXTS.MCH_EN_NAME,
    LANGUAGE_TEXTS.DNC_EN_NAME,
    LANGUAGE_TEXTS.BLM_EN_NAME,
    LANGUAGE_TEXTS.SMN_EN_NAME,
    LANGUAGE_TEXTS.RDM_EN_NAME,
    LANGUAGE_TEXTS.PCT_EN_NAME,
  ];

  const AUTO_ATTACK_DELAYS: Map<string, number> = new Map([
    [LANGUAGE_TEXTS.PLD_EN_NAME, 2.24],
    [LANGUAGE_TEXTS.WAR_EN_NAME, 3.36],
    [LANGUAGE_TEXTS.DRK_EN_NAME, 2.96],
    [LANGUAGE_TEXTS.GNB_EN_NAME, 2.8],
    [LANGUAGE_TEXTS.DRG_EN_NAME, 2.8],
    [LANGUAGE_TEXTS.RPR_EN_NAME, 3.2],
    [LANGUAGE_TEXTS.MNK_EN_NAME, 2.56],
    [LANGUAGE_TEXTS.SAM_EN_NAME, 2.64],
    [LANGUAGE_TEXTS.NIN_EN_NAME, 2.56],
    [LANGUAGE_TEXTS.VPR_EN_NAME, 2.64],
    [LANGUAGE_TEXTS.BRD_EN_NAME, 3.04],
    [LANGUAGE_TEXTS.MCH_EN_NAME, 2.64],
    [LANGUAGE_TEXTS.DNC_EN_NAME, 3.12],
  ]);

  return { ALL_PLAYER_JOBS, AUTO_ATTACK_DELAYS };
}

