use crate::event::ffxiv_event::FfxivEvent::{
    AddTicker, ApplyBuff, ApplyBuffStack, ApplyDebuff, ApplyRaidBuff,
};
use crate::event::FfxivEventQueue;
use crate::event_ticker::auto_attack_ticker::AutoAttackTicker;
use crate::event_ticker::ffxiv_event_ticker::FfxivEventTicker;
use crate::id_entity::IdEntity;
use crate::jobs_skill_data::PotionSkill;
use crate::rotation::SkillTable;
use crate::skill::attack_skill::AttackSkill;
use crate::skill::damage_category::DamageCategory;
use crate::skill::use_type::UseType;
use crate::skill::ResourceRequirements::{CheckStatus, Resource, UseBuff};
use crate::skill::{make_skill_table, ResourceRequirements};
use crate::status::buff_status::BuffStatus;
use crate::status::debuff_status::DebuffStatus;
use crate::status::status_info::StatusInfo;
use crate::IdType;
use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

pub(crate) struct SummonerDatabase {
    pub(crate) ruin_iii: AttackSkill,
    pub(crate) ruin_iv: AttackSkill,
    pub(crate) searing_light: AttackSkill,
    pub(crate) energy_drain: AttackSkill,
    pub(crate) necrotize: AttackSkill,
    pub(crate) summon_bahamut: AttackSkill,
    pub(crate) enkindle_bahamut: AttackSkill,
    pub(crate) deathflare: AttackSkill,
    pub(crate) astral_impulse: AttackSkill,
    pub(crate) wyrmwave: AttackSkill,
    pub(crate) summon_ifrit_ii: AttackSkill,
    pub(crate) crimson_cyclone: AttackSkill,
    pub(crate) crimson_strike: AttackSkill,
    pub(crate) ruby_rite: AttackSkill,
    pub(crate) summon_titan_ii: AttackSkill,
    pub(crate) topaz_rite: AttackSkill,
    pub(crate) mountain_buster: AttackSkill,
    pub(crate) summon_garuda_ii: AttackSkill,
    pub(crate) emerald_rite: AttackSkill,
    pub(crate) slipstream: AttackSkill,
    pub(crate) summon_phoenix: AttackSkill,
    pub(crate) fountain_of_fire: AttackSkill,
    pub(crate) enkindle_phoenix: AttackSkill,
    pub(crate) scarlet_flame: AttackSkill,
    pub(crate) transform: AttackSkill,
    pub(crate) searing_flash: AttackSkill,
    pub(crate) summon_solar_bahamut: AttackSkill,
    pub(crate) umbral_impulse: AttackSkill,
    pub(crate) sunflare: AttackSkill,
    pub(crate) enkindle_solar_bahamut: AttackSkill,
    pub(crate) luxwave: AttackSkill,

    pub(crate) further_ruin: BuffStatus,
    pub(crate) searing_light_buff: BuffStatus,
    pub(crate) bahamut_state: BuffStatus,
    pub(crate) phoenix_state: BuffStatus,
    pub(crate) ifrit_state: BuffStatus,
    pub(crate) titan_state: BuffStatus,
    pub(crate) garuda_state: BuffStatus,
    pub(crate) titans_favor: BuffStatus,
    pub(crate) slipstream_dot: DebuffStatus,
    pub(crate) solar_bahamut_state: BuffStatus,
    pub(crate) rubys_glimmer: BuffStatus,

    pub(crate) potion: AttackSkill,
    pub(crate) potion_buff: BuffStatus,
}

impl SummonerDatabase {
    pub(crate) fn new(player_id: IdType, ffxiv_event_queue: Rc<RefCell<FfxivEventQueue>>) -> Self {
        let FURTHER_RUIN: BuffStatus = BuffStatus {
            id: 1600,
            name: String::from("Further Ruin"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 60000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let SEARING_LIGHT_BUFF: BuffStatus = BuffStatus {
            id: 1601,
            name: String::from("Searing Light"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::DamagePercent(5)],
            duration_millisecond: 20000,
            is_raidwide: true,
            trigger_proc_event_on_gcd: vec![],
        };
        let BAHAMUT_STATE: BuffStatus = BuffStatus {
            id: 1602,
            name: String::from("Bahamut State"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 15000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let PHOENIX_STATE: BuffStatus = BuffStatus {
            id: 1603,
            name: String::from("Phoenix State"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 15000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };

        let IFRIT_STATE: BuffStatus = BuffStatus {
            id: 1604,
            name: String::from("Ifrit State"),
            stacks: 2,
            max_stacks: 2,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };

        let TITAN_STATE: BuffStatus = BuffStatus {
            id: 1605,
            name: String::from("Titan State"),
            stacks: 4,
            max_stacks: 4,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };

        let GARUDA_STATE: BuffStatus = BuffStatus {
            id: 1606,
            name: String::from("Garuda State"),
            stacks: 4,
            max_stacks: 4,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };

        let TITANS_FAVOR: BuffStatus = BuffStatus {
            id: 1607,
            name: String::from("Titan's Favor"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 10000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };

        let SLIPSTREAM_DOT: DebuffStatus = DebuffStatus {
            id: 1608,
            name: String::from("Slipstream"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            damage_skill_id: Some(1619),
            potency: Some(30),
            trait_percent: Some(130),
            damage_category: Some(DamageCategory::MagicalDot),
            duration_left_millisecond: 0,
            status_info: vec![],
            duration_millisecond: 15000,
            is_raidwide: false,
            snapshotted_debuffs: Default::default(),
            snapshotted_buffs: Default::default(),
        };
        let SOLAR_BAHAMUT_STATE: BuffStatus = BuffStatus {
            id: 1609,
            name: String::from("Solar Bahamut State"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 15000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let RUBYS_GLIMMER: BuffStatus = BuffStatus {
            id: 1610,
            name: String::from("Ruby's Glimmer"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };

        let WYRMWAVE: AttackSkill = AttackSkill {
            id: 1609,
            name: String::from("Wyrmwave"),
            player_id,
            potency: 150,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let SCARLET_FLAME: AttackSkill = AttackSkill {
            id: 1623,
            name: String::from("Scarlet Flame"),
            player_id,
            potency: 150,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let LUXWAVE: AttackSkill = AttackSkill {
            id: 1630,
            name: String::from("Luxwave"),
            player_id,
            potency: 200,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let TRANSFORM: AttackSkill = AttackSkill {
            id: 1624,
            name: String::from("Transform"),
            player_id,
            potency: 0,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 60000,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::NoTarget,
        };

        let wyrmwave_ticker = AutoAttackTicker::new_with_auto_attack(
            1600,
            player_id,
            WYRMWAVE.clone(),
            DamageCategory::Direct,
            15000,
            ffxiv_event_queue.clone(),
        );
        let phoenix_ticker = AutoAttackTicker::new_with_auto_attack(
            1601,
            player_id,
            SCARLET_FLAME.clone(),
            DamageCategory::Direct,
            15000,
            ffxiv_event_queue.clone(),
        );
        let solar_bahamut_ticker = AutoAttackTicker::new_with_auto_attack(
            1602,
            player_id,
            LUXWAVE.clone(),
            DamageCategory::Direct,
            15000,
            ffxiv_event_queue.clone(),
        );

        let RUIN_III: AttackSkill = AttackSkill {
            id: 1600,
            name: String::from("Ruin III"),
            player_id,
            potency: 310,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let RUIN_IV: AttackSkill = AttackSkill {
            id: 1601,
            name: String::from("Ruin IV"),
            player_id,
            potency: 430,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(FURTHER_RUIN.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let SEARING_LIGHT: AttackSkill = AttackSkill {
            id: 1602,
            name: String::from("Searing Light"),
            player_id,
            potency: 0,
            trait_percent: 130,
            additional_skill_events: vec![ApplyRaidBuff(
                player_id,
                SEARING_LIGHT_BUFF.clone(),
                30000,
                30000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 120000,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::NoTarget,
        };
        let ENERGY_DRAIN: AttackSkill = AttackSkill {
            id: 1603,
            name: String::from("Energy Drain"),
            player_id,
            potency: 200,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 60000,
            resource_required: vec![],
            resource_created: HashMap::from([(0, 2)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let NECROTIZE: AttackSkill = AttackSkill {
            id: 1604,
            name: String::from("Necrotize"),
            player_id,
            potency: 420,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::Resource(0, 1)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let SUMMON_BAHAMUT: AttackSkill = AttackSkill {
            id: 1605,
            name: String::from("Summon Bahamut"),
            player_id,
            potency: 0,
            trait_percent: 130,
            additional_skill_events: vec![
                ApplyBuff(player_id, player_id, BAHAMUT_STATE.clone(), 15000, 15000, 0),
                AddTicker(FfxivEventTicker::AutoAttackTicker(wyrmwave_ticker), 0),
            ],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 60000,
            resource_required: vec![],
            resource_created: HashMap::from([(1, 1), (2, 1), (3, 1), (4, 1), (5, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: Some(TRANSFORM.get_id()),
            is_guaranteed_direct_hit: false,
            use_type: UseType::NoTarget,
        };
        let ENKINDLE_BAHAMUT: AttackSkill = AttackSkill {
            id: 1606,
            name: String::from("Enkindle Bahamut"),
            player_id,
            potency: 1300,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 20000,
            resource_required: vec![ResourceRequirements::CheckStatus(BAHAMUT_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let DEATHFLARE: AttackSkill = AttackSkill {
            id: 1607,
            name: String::from("Deathflare"),
            player_id,
            potency: 500,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 20000,
            resource_required: vec![ResourceRequirements::CheckStatus(BAHAMUT_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let ASTRAL_IMPULSE: AttackSkill = AttackSkill {
            id: 1608,
            name: String::from("Astral Impulse"),
            player_id,
            potency: 440,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::CheckStatus(BAHAMUT_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let SUMMON_IFRIT_II: AttackSkill = AttackSkill {
            id: 1610,
            name: String::from("Summon Ifrit II"),
            player_id,
            potency: 800,
            trait_percent: 130,
            additional_skill_events: vec![ApplyBuffStack(
                player_id,
                player_id,
                IFRIT_STATE.clone(),
                30000,
                true,
                0,
            )],
            proc_events: vec![],
            combo: Some(0),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::Resource(1, 1)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let CRIMSON_CYCLONE: AttackSkill = AttackSkill {
            id: 1611,
            name: String::from("Crimson Cyclone"),
            player_id,
            potency: 490,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(1),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 30000,
            resource_required: vec![CheckStatus(IFRIT_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let CRIMSON_STRIKE: AttackSkill = AttackSkill {
            id: 1612,
            name: String::from("Crimson Strike"),
            player_id,
            potency: 490,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(2),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 30000,
            resource_required: vec![CheckStatus(IFRIT_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let RUBY_RITE: AttackSkill = AttackSkill {
            id: 1613,
            name: String::from("Ruby Rite"),
            player_id,
            potency: 540,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 2800,
            gcd_cooldown_millisecond: 3000,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::UseBuff(IFRIT_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let SUMMON_TITAN_II: AttackSkill = AttackSkill {
            id: 1614,
            name: String::from("Summon Titan II"),
            player_id,
            potency: 800,
            trait_percent: 130,
            additional_skill_events: vec![ApplyBuffStack(
                player_id,
                player_id,
                TITAN_STATE.clone(),
                30000,
                true,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::Resource(2, 1)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let TOPAZ_RITE: AttackSkill = AttackSkill {
            id: 1615,
            name: String::from("Topaz Rite"),
            player_id,
            potency: 340,
            trait_percent: 130,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                TITANS_FAVOR.clone(),
                10000,
                10000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(TITAN_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let MOUNTAIN_BUSTER: AttackSkill = AttackSkill {
            id: 1616,
            name: String::from("Mountain Buster"),
            player_id,
            potency: 160,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(TITANS_FAVOR.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let SUMMON_GARUDA_II: AttackSkill = AttackSkill {
            id: 1617,
            name: String::from("Summon Garuda II"),
            player_id,
            potency: 800,
            trait_percent: 130,
            additional_skill_events: vec![ApplyBuffStack(
                player_id,
                player_id,
                GARUDA_STATE.clone(),
                30000,
                true,
                0,
            )],
            proc_events: vec![],
            combo: Some(3),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::Resource(3, 1)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let EMERALD_RITE: AttackSkill = AttackSkill {
            id: 1618,
            name: String::from("Emerald Rite"),
            player_id,
            potency: 240,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 1500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(GARUDA_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let SLIPSTREAM: AttackSkill = AttackSkill {
            id: 1619,
            name: String::from("Slipstream"),
            player_id,
            potency: 490,
            trait_percent: 130,
            additional_skill_events: vec![ApplyDebuff(
                player_id,
                SLIPSTREAM_DOT.clone(),
                15000,
                15000,
                0,
            )],
            proc_events: vec![],
            combo: Some(4),
            delay_millisecond: None,
            casting_time_millisecond: 3000,
            gcd_cooldown_millisecond: 3500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![CheckStatus(GARUDA_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let SUMMON_PHOENIX: AttackSkill = AttackSkill {
            id: 1620,
            name: String::from("Summon Phoenix"),
            player_id,
            potency: 0,
            trait_percent: 130,
            additional_skill_events: vec![
                ApplyBuff(player_id, player_id, PHOENIX_STATE.clone(), 15000, 15000, 0),
                AddTicker(FfxivEventTicker::AutoAttackTicker(phoenix_ticker), 0),
            ],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 60000,
            resource_required: vec![ResourceRequirements::Resource(4, 1)],
            resource_created: HashMap::from([(1, 1), (2, 1), (3, 1), (5, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: Some(TRANSFORM.get_id()),
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let FOUNTAIN_OF_FIRE: AttackSkill = AttackSkill {
            id: 1621,
            name: String::from("Fountain of Fire"),
            player_id,
            potency: 580,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![CheckStatus(PHOENIX_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let ENKINDLE_PHOENIX: AttackSkill = AttackSkill {
            id: 1622,
            name: String::from("Enkindle Phoenix"),
            player_id,
            potency: 1300,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 20000,
            resource_required: vec![ResourceRequirements::CheckStatus(PHOENIX_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let SEARING_FLASH: AttackSkill = AttackSkill {
            id: 1625,
            name: String::from("Searing Flash"),
            player_id,
            potency: 600,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(RUBYS_GLIMMER.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let SEARING_FLASH: AttackSkill = AttackSkill {
            id: 1625,
            name: String::from("Searing Flash"),
            player_id,
            potency: 600,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(RUBYS_GLIMMER.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let SUMMON_SOLAR_BAHAMUT: AttackSkill = AttackSkill {
            id: 1626,
            name: String::from("Summon Solar Bahamut"),
            player_id,
            potency: 0,
            trait_percent: 130,
            additional_skill_events: vec![
                ApplyBuff(
                    player_id,
                    player_id,
                    SOLAR_BAHAMUT_STATE.clone(),
                    15000,
                    15000,
                    0,
                ),
                AddTicker(FfxivEventTicker::AutoAttackTicker(solar_bahamut_ticker), 0),
            ],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 60000,
            resource_required: vec![Resource(5, 1)],
            resource_created: HashMap::from([(1, 1), (2, 1), (3, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: Some(TRANSFORM.get_id()),
            is_guaranteed_direct_hit: false,
            use_type: UseType::NoTarget,
        };
        let UMBRAL_IMPULSE: AttackSkill = AttackSkill {
            id: 1627,
            name: String::from("Umbral Impulse"),
            player_id,
            potency: 600,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![CheckStatus(SOLAR_BAHAMUT_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: Some(TRANSFORM.get_id()),
            is_guaranteed_direct_hit: false,
            use_type: UseType::NoTarget,
        };
        let SUNFLARE: AttackSkill = AttackSkill {
            id: 1628,
            name: String::from("Sunflare"),
            player_id,
            potency: 600,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 20000,
            resource_required: vec![CheckStatus(SOLAR_BAHAMUT_STATE.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: Some(TRANSFORM.get_id()),
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let ENKINDLE_SOLAR_BAHAMUT: AttackSkill = AttackSkill {
            id: 1629,
            name: String::from("Enkindle Solar Bahamut"),
            player_id,
            potency: 1400,
            trait_percent: 130,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 20000,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: Some(TRANSFORM.get_id()),
            is_guaranteed_direct_hit: false,
            use_type: UseType::NoTarget,
        };

        let potion_skill = PotionSkill::new(player_id);

        SummonerDatabase {
            ruin_iii: RUIN_III,
            ruin_iv: RUIN_IV,
            searing_light: SEARING_LIGHT,
            energy_drain: ENERGY_DRAIN,

            necrotize: NECROTIZE,
            summon_bahamut: SUMMON_BAHAMUT,
            enkindle_bahamut: ENKINDLE_BAHAMUT,
            deathflare: DEATHFLARE,
            astral_impulse: ASTRAL_IMPULSE,
            wyrmwave: WYRMWAVE,
            summon_ifrit_ii: SUMMON_IFRIT_II,
            crimson_cyclone: CRIMSON_CYCLONE,
            crimson_strike: CRIMSON_STRIKE,
            ruby_rite: RUBY_RITE,
            summon_titan_ii: SUMMON_TITAN_II,
            topaz_rite: TOPAZ_RITE,
            mountain_buster: MOUNTAIN_BUSTER,
            summon_garuda_ii: SUMMON_GARUDA_II,
            emerald_rite: EMERALD_RITE,
            slipstream: SLIPSTREAM,
            summon_phoenix: SUMMON_PHOENIX,
            fountain_of_fire: FOUNTAIN_OF_FIRE,
            enkindle_phoenix: ENKINDLE_PHOENIX,
            scarlet_flame: SCARLET_FLAME,
            transform: TRANSFORM,
            searing_flash: SEARING_FLASH,
            summon_solar_bahamut: SUMMON_SOLAR_BAHAMUT,
            umbral_impulse: UMBRAL_IMPULSE,
            sunflare: SUNFLARE,
            enkindle_solar_bahamut: ENKINDLE_SOLAR_BAHAMUT,
            luxwave: LUXWAVE,

            further_ruin: FURTHER_RUIN,
            searing_light_buff: SEARING_LIGHT_BUFF,
            bahamut_state: BAHAMUT_STATE,
            phoenix_state: PHOENIX_STATE,
            ifrit_state: IFRIT_STATE,
            titan_state: TITAN_STATE,
            garuda_state: GARUDA_STATE,
            titans_favor: TITANS_FAVOR,
            slipstream_dot: SLIPSTREAM_DOT,
            rubys_glimmer: RUBYS_GLIMMER,
            solar_bahamut_state: SOLAR_BAHAMUT_STATE,

            potion: potion_skill.potion,
            potion_buff: potion_skill.potion_buff,
        }
    }
}

pub(crate) fn make_summoner_skill_list(
    player_id: IdType,
    ffxiv_event_queue: Rc<RefCell<FfxivEventQueue>>,
) -> SkillTable<AttackSkill> {
    let db = SummonerDatabase::new(player_id, ffxiv_event_queue);

    let summoner_skill_list: Vec<AttackSkill> = vec![
        db.ruin_iii,
        db.ruin_iv,
        db.searing_light,
        db.energy_drain,
        db.necrotize,
        db.summon_bahamut,
        db.enkindle_bahamut,
        db.deathflare,
        db.astral_impulse,
        db.wyrmwave,
        db.summon_ifrit_ii,
        db.crimson_cyclone,
        db.crimson_strike,
        db.ruby_rite,
        db.summon_titan_ii,
        db.topaz_rite,
        db.mountain_buster,
        db.summon_garuda_ii,
        db.emerald_rite,
        db.slipstream,
        db.summon_phoenix,
        db.fountain_of_fire,
        db.enkindle_phoenix,
        db.scarlet_flame,
        db.transform,
        db.searing_flash,
        db.summon_solar_bahamut,
        db.umbral_impulse,
        db.sunflare,
        db.enkindle_solar_bahamut,
        db.luxwave,
        db.potion,
    ];

    make_skill_table(summoner_skill_list)
}
