use crate::event::ffxiv_event::FfxivEvent;
use crate::event::ffxiv_event::FfxivEvent::{ApplyBuff, ApplyRaidBuff};
use crate::rotation::SkillTable;
use crate::skill::attack_skill::AttackSkill;
use crate::skill::damage_category::DamageCategory;
use crate::skill::use_type::UseType;
use crate::skill::{make_skill_table, ResourceRequirements};
use crate::status::buff_status::BuffStatus;
use crate::status::debuff_status::DebuffStatus;
use crate::status::status_info::StatusInfo;
use crate::IdType;
use std::collections::HashMap;

pub(crate) struct MonkDatabase {
    pub(crate) bootshine: AttackSkill,
    pub(crate) true_strike: AttackSkill,
    pub(crate) snap_punch: AttackSkill,
    pub(crate) twin_snakes: AttackSkill,
    pub(crate) demolish: AttackSkill,
    pub(crate) dragon_kick: AttackSkill,
    pub(crate) elixir_field: AttackSkill,
    pub(crate) rising_pheonix: AttackSkill,
    pub(crate) phantom_rush: AttackSkill,
    pub(crate) brotherhood: AttackSkill,
    pub(crate) riddle_of_fire: AttackSkill,
    pub(crate) riddle_of_wind: AttackSkill,
    pub(crate) perfect_balance: AttackSkill,
    pub(crate) the_forbidden_chakra: AttackSkill,
    pub(crate) perfect_bootshine: AttackSkill,
    pub(crate) perfect_true_strike: AttackSkill,
    pub(crate) perfect_snap_punch: AttackSkill,
    pub(crate) perfect_twin_snakes: AttackSkill,
    pub(crate) perfect_demolish: AttackSkill,
    pub(crate) perfect_dragon_kick: AttackSkill,

    pub(crate) disciplined_fist: BuffStatus,
    pub(crate) leaden_fist: BuffStatus,
    pub(crate) demolish_dot: DebuffStatus,
    pub(crate) perfect_balance_buff: BuffStatus,
    pub(crate) riddle_of_fire_buff: BuffStatus,
    pub(crate) riddle_of_wind_buff: BuffStatus,
    pub(crate) brotherhood_damage_buff: BuffStatus,
    pub(crate) brotherhood_proc_buff: BuffStatus,
}

impl MonkDatabase {
    pub(crate) fn new(player_id: IdType) -> Self {
        let DISCIPLINED_FIST: BuffStatus = BuffStatus {
            id: 900,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::DamagePercent(15)],
            duration_millisecond: 30000,
            is_raidwide: false,
            name: "Disciplined Fist".to_string(),
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let LEADEN_FIST: BuffStatus = BuffStatus {
            id: 901,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            name: "Leaden Fist".to_string(),
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let DEMOLISH_DOT: DebuffStatus = DebuffStatus {
            id: 902,
            owner_id: player_id,
            potency: Some(70),
            damage_skill_id: Some(904),
            trait_percent: Some(100),
            damage_category: Some(DamageCategory::PhysicalDot),
            duration_left_millisecond: 0,
            status_info: vec![],
            duration_millisecond: 18000,
            is_raidwide: false,
            name: "Demolish Dot".to_string(),
            snapshotted_buffs: Default::default(),
            stacks: 1,
            max_stacks: 1,
            snapshotted_debuffs: Default::default(),
        };
        let PERFECT_BALANCE_BUFF: BuffStatus = BuffStatus {
            id: 903,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 20000,
            is_raidwide: true,
            name: "Perfect Balance Status".to_string(),
            stacks: 3,
            max_stacks: 3,
            trigger_proc_event_on_gcd: vec![],
        };
        let RIDDLE_OF_FIRE_BUFF: BuffStatus = BuffStatus {
            id: 904,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::DamagePercent(15)],
            duration_millisecond: 20000,
            is_raidwide: false,
            name: "Riddle of Fire Buff".to_string(),
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let RIDDLE_OF_WIND_BUFF: BuffStatus = BuffStatus {
            id: 905,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::SpeedOnlyAutoAttack(50)],
            duration_millisecond: 15000,
            is_raidwide: false,
            name: "Riddle of Wind Buff".to_string(),
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let BROTHERHOOD_DAMAGE_BUFF: BuffStatus = BuffStatus {
            id: 906,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::DamagePercent(5)],
            duration_millisecond: 15000,
            is_raidwide: true,
            name: "Brotherhood Damage Buff".to_string(),
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let BROTHERHOOD_RAID_PROC: BuffStatus = BuffStatus {
            id: 907,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 15000,
            is_raidwide: true,
            name: "Brotherhood Raid Proc".to_string(),
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![(
                FfxivEvent::IncreasePlayerResource(player_id, 0, 1, 0),
                20,
            )],
        };
        let BROTHERHOOD_PERSONAL_PROC: BuffStatus = BuffStatus {
            id: 908,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 15000,
            is_raidwide: false,
            name: "Brotherhood Personal Proc".to_string(),
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![(
                FfxivEvent::IncreasePlayerResource(player_id, 0, 1, 0),
                100,
            )],
        };

        let BOOTSHINE: AttackSkill = AttackSkill {
            id: 900,
            name: "Bootshine".to_string(),
            player_id,
            potency: 310,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(2),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![ResourceRequirements::UseBuff(LEADEN_FIST.id)],
            resource_created: HashMap::from([(0, 1)]),
            is_guaranteed_crit: true,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let TRUE_STRIKE: AttackSkill = AttackSkill {
            id: 901,
            name: "True Strike".to_string(),
            player_id,
            potency: 300,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(3),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let SNAP_PUNCH: AttackSkill = AttackSkill {
            id: 902,
            name: "Snap Punch".to_string(),
            player_id,
            potency: 310,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(1),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let TWIN_SNAKES: AttackSkill = AttackSkill {
            id: 903,
            name: "Twin Snakes".to_string(),
            player_id,
            potency: 280,
            trait_percent: 100,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                DISCIPLINED_FIST.clone(),
                30000,
                30000,
                0,
            )],
            proc_events: vec![],
            combo: Some(3),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let DEMOLISH: AttackSkill = AttackSkill {
            id: 904,
            name: "Demolish".to_string(),
            player_id,
            potency: 130,
            trait_percent: 100,
            additional_skill_events: vec![FfxivEvent::ApplyDebuff(
                player_id,
                DEMOLISH_DOT.clone(),
                18000,
                18000,
                0,
            )],
            proc_events: vec![],
            combo: Some(1),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let DRAGON_KICK: AttackSkill = AttackSkill {
            id: 905,
            name: "Dragon Kick".to_string(),
            player_id,
            potency: 320,
            trait_percent: 100,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                LEADEN_FIST.clone(),
                30000,
                30000,
                0,
            )],
            proc_events: vec![],
            combo: Some(2),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let ELIXIR_FIELD: AttackSkill = AttackSkill {
            id: 906,
            name: "Elixir Field".to_string(),
            player_id,
            potency: 600,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(1),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![ResourceRequirements::Resource(1, 3)],
            resource_created: HashMap::from([(4, 1)]),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let RISING_PHEONIX: AttackSkill = AttackSkill {
            id: 907,
            name: "Rising Pheonix".to_string(),
            player_id,
            potency: 700,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(1),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![
                ResourceRequirements::Resource(1, 1),
                ResourceRequirements::Resource(2, 1),
                ResourceRequirements::Resource(3, 1),
            ],
            resource_created: HashMap::from([(5, 1)]),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };
        let PHANTOM_RUSH: AttackSkill = AttackSkill {
            id: 908,
            name: "Phantom Rush".to_string(),
            player_id,
            potency: 1150,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(1),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![
                ResourceRequirements::Resource(4, 1),
                ResourceRequirements::Resource(5, 1),
                ResourceRequirements::Resource(1, 3),
            ],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let BROTHERHOOD: AttackSkill = AttackSkill {
            id: 909,
            name: "Brotherhood".to_string(),
            player_id,
            potency: 0,
            trait_percent: 100,
            additional_skill_events: vec![
                ApplyRaidBuff(player_id, BROTHERHOOD_DAMAGE_BUFF.clone(), 15000, 15000, 0),
                ApplyRaidBuff(player_id, BROTHERHOOD_RAID_PROC.clone(), 15000, 15000, 0),
                ApplyBuff(
                    player_id,
                    player_id,
                    BROTHERHOOD_PERSONAL_PROC.clone(),
                    15000,
                    15000,
                    0,
                ),
                FfxivEvent::RemoveTargetBuff(player_id, player_id, BROTHERHOOD_RAID_PROC.id, 0),
            ],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 120000,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::NoTarget,
        };
        let RIDDLE_OF_FIRE: AttackSkill = AttackSkill {
            id: 910,
            name: "Riddle of Fire".to_string(),
            player_id,
            potency: 0,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                RIDDLE_OF_FIRE_BUFF.clone(),
                20000,
                20000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 60000,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::NoTarget,
        };
        let RIDDLE_OF_WIND: AttackSkill = AttackSkill {
            id: 911,
            name: "Riddle of Wind".to_string(),
            player_id,
            potency: 0,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                RIDDLE_OF_WIND_BUFF.clone(),
                15000,
                15000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            resource_required: vec![ResourceRequirements::Resource(0, 50)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 90000,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::NoTarget,
        };

        let PERFECT_BALANCE: AttackSkill = AttackSkill {
            id: 912,
            name: "Perfect Balance".to_string(),
            player_id,
            potency: 0,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                PERFECT_BALANCE_BUFF.clone(),
                20000,
                20000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 40000,
            current_cooldown_millisecond: 0,
            stacks: 2,
            stack_skill_id: None,
            use_type: UseType::NoTarget,
        };

        let THE_FORBIDDEN_CHAKRA: AttackSkill = AttackSkill {
            id: 913,
            name: "The Forbidden Chakra".to_string(),
            player_id,
            potency: 340,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            resource_required: vec![ResourceRequirements::Resource(0, 5)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 1000,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let PERFECT_BOOTSHINE: AttackSkill = AttackSkill {
            id: 914,
            name: "Perfect Bootshine".to_string(),
            player_id,
            potency: 310,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![ResourceRequirements::UseBuff(PERFECT_BALANCE_BUFF.id)],
            resource_created: HashMap::from([(0, 1), (1, 1)]),
            is_guaranteed_crit: true,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let PERFECT_TRUE_STRIKE: AttackSkill = AttackSkill {
            id: 915,
            name: "Perfect True Strike".to_string(),
            player_id,
            potency: 300,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![],
            resource_created: HashMap::from([(2, 1)]),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let PERFECT_SNAP_PUNCH: AttackSkill = AttackSkill {
            id: 916,
            name: "Perfect Snap Punch".to_string(),
            player_id,
            potency: 310,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![ResourceRequirements::UseBuff(PERFECT_BALANCE_BUFF.id)],
            resource_created: HashMap::from([(3, 1)]),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let PERFECT_TWIN_SNAKES: AttackSkill = AttackSkill {
            id: 917,
            name: "Perfect Twin Snakes".to_string(),
            player_id,
            potency: 280,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                DISCIPLINED_FIST.clone(),
                30000,
                30000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![ResourceRequirements::UseBuff(PERFECT_BALANCE_BUFF.id)],
            resource_created: HashMap::from([(3, 1)]),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let PERFECT_DEMOLISH: AttackSkill = AttackSkill {
            id: 918,
            name: "Perfect Demolish".to_string(),
            player_id,
            potency: 130,
            trait_percent: 100,
            additional_skill_events: vec![FfxivEvent::ApplyDebuff(
                player_id,
                DEMOLISH_DOT.clone(),
                18000,
                18000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![ResourceRequirements::UseBuff(PERFECT_BALANCE_BUFF.id)],
            resource_created: HashMap::from([(3, 1)]),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        let PERFECT_DRAGON_KICK: AttackSkill = AttackSkill {
            id: 919,
            name: "Dragon Kick".to_string(),
            player_id,
            potency: 320,
            trait_percent: 100,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                LEADEN_FIST.clone(),
                30000,
                30000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            resource_required: vec![ResourceRequirements::UseBuff(PERFECT_BALANCE_BUFF.id)],
            resource_created: HashMap::from([(1, 1)]),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
            cooldown_millisecond: 0,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            use_type: UseType::UseOnTarget,
        };

        MonkDatabase {
            bootshine: BOOTSHINE,
            true_strike: TRUE_STRIKE,
            snap_punch: SNAP_PUNCH,
            twin_snakes: TWIN_SNAKES,
            demolish: DEMOLISH,
            dragon_kick: DRAGON_KICK,
            elixir_field: ELIXIR_FIELD,
            rising_pheonix: RISING_PHEONIX,
            phantom_rush: PHANTOM_RUSH,
            brotherhood: BROTHERHOOD,
            riddle_of_fire: RIDDLE_OF_FIRE,
            riddle_of_wind: RIDDLE_OF_WIND,
            perfect_balance: PERFECT_BALANCE,
            the_forbidden_chakra: THE_FORBIDDEN_CHAKRA,
            perfect_bootshine: PERFECT_BOOTSHINE,
            perfect_true_strike: PERFECT_TRUE_STRIKE,
            perfect_snap_punch: PERFECT_SNAP_PUNCH,
            perfect_twin_snakes: PERFECT_TWIN_SNAKES,
            perfect_demolish: PERFECT_DEMOLISH,
            perfect_dragon_kick: PERFECT_DRAGON_KICK,
            disciplined_fist: DISCIPLINED_FIST,
            leaden_fist: LEADEN_FIST,
            demolish_dot: DEMOLISH_DOT,
            perfect_balance_buff: PERFECT_BALANCE_BUFF,
            riddle_of_fire_buff: RIDDLE_OF_FIRE_BUFF,
            riddle_of_wind_buff: RIDDLE_OF_WIND_BUFF,
            brotherhood_damage_buff: BROTHERHOOD_DAMAGE_BUFF,
            brotherhood_proc_buff: BROTHERHOOD_RAID_PROC,
        }
    }
}

pub(crate) fn make_monk_skill_list(player_id: IdType) -> SkillTable<AttackSkill> {
    let db = MonkDatabase::new(player_id);

    let monk_skill_list: Vec<AttackSkill> = vec![
        db.bootshine,
        db.true_strike,
        db.snap_punch,
        db.twin_snakes,
        db.demolish,
        db.dragon_kick,
        db.elixir_field,
        db.rising_pheonix,
        db.phantom_rush,
        db.brotherhood,
        db.riddle_of_fire,
        db.riddle_of_wind,
        db.perfect_balance,
        db.the_forbidden_chakra,
        db.perfect_bootshine,
        db.perfect_true_strike,
        db.perfect_snap_punch,
        db.perfect_twin_snakes,
        db.perfect_demolish,
        db.perfect_dragon_kick,
    ];

    make_skill_table(monk_skill_list)
}
