use crate::event::ffxiv_event::FfxivEvent::{ApplyBuff, ApplyDebuff};
use crate::id_entity::IdEntity;
use crate::jobs_skill_data::PotionSkill;
use crate::rotation::SkillTable;
use crate::skill::attack_skill::AttackSkill;
use crate::skill::damage_category::DamageCategory;
use crate::skill::use_type::UseType;
use crate::skill::ResourceRequirements::{Resource, UseBuff};
use crate::skill::{make_skill_table, ResourceRequirements};
use crate::status::buff_status::BuffStatus;
use crate::status::debuff_status::DebuffStatus;
use crate::status::status_info::StatusInfo;
use crate::types::{IdType, PlayerIdType};
use std::collections::HashMap;

pub(crate) struct SamuraiDatabase {
    pub(crate) gyofu: AttackSkill,
    pub(crate) jinpu: AttackSkill,
    pub(crate) gekko: AttackSkill,
    pub(crate) shifu: AttackSkill,
    pub(crate) kasha: AttackSkill,
    pub(crate) yukikaze: AttackSkill,
    pub(crate) hissatsu_shinten: AttackSkill,
    pub(crate) hissatsu_senei: AttackSkill,
    pub(crate) meikyo_shisui: AttackSkill,
    pub(crate) gekko_meikyo: AttackSkill,
    pub(crate) kasha_meikyo: AttackSkill,
    pub(crate) yuki_meikyo: AttackSkill,
    pub(crate) ikishoten: AttackSkill,
    pub(crate) hagakure: AttackSkill,
    pub(crate) kaeshi_tendo_setsugekka: AttackSkill,
    pub(crate) ogi_namikiri: AttackSkill,
    pub(crate) kaeshi_namikiri: AttackSkill,
    pub(crate) higanbana: AttackSkill,
    pub(crate) midare_setsugekka: AttackSkill,
    pub(crate) shoha: AttackSkill,
    pub(crate) higanbana_two: AttackSkill,
    pub(crate) higanbana_three: AttackSkill,
    pub(crate) zanshin: AttackSkill,
    pub(crate) tendo_setsugekka: AttackSkill,
    pub(crate) kaeshi_setsugekka: AttackSkill,

    pub(crate) tendo_setsugekka_used: BuffStatus,
    pub(crate) ogi_namikiri_ready: BuffStatus,
    pub(crate) fugetsu: BuffStatus,
    pub(crate) fuka: BuffStatus,
    pub(crate) higanbana_dot: DebuffStatus,
    pub(crate) ogi_namikiri_used: BuffStatus,
    pub(crate) midare_used: BuffStatus,
    pub(crate) zanshin_ready: BuffStatus,
    pub(crate) tendo: BuffStatus,
    pub(crate) meikyo_shisui_buff: BuffStatus,

    pub(crate) potion: AttackSkill,
    pub(crate) potion_buff: BuffStatus,
}

impl SamuraiDatabase {
    pub(crate) fn new(player_id: PlayerIdType) -> Self {
        let MEIKYO_SHISUI_BUFF: BuffStatus = BuffStatus {
            id: 1100,
            name: String::from("Meikyo Shisui"),
            stacks: 3,
            max_stacks: 3,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 15000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let TENDO_SETSUGEKKA_USED: BuffStatus = BuffStatus {
            id: 1101,
            name: String::from("Tendo Setsugekka Used"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let OGI_NAMIKIRI_READY: BuffStatus = BuffStatus {
            id: 1102,
            name: String::from("Ogi Namikiri Ready"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let FUGETSU: BuffStatus = BuffStatus {
            id: 1103,
            name: String::from("Fugetsu"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::SpeedPercent(13)],
            duration_millisecond: 40000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let FUKA: BuffStatus = BuffStatus {
            id: 1104,
            name: String::from("Fuka"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::DamagePercent(13)],
            duration_millisecond: 40000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let HIGANBANA_DOT: DebuffStatus = DebuffStatus {
            id: 1105,
            name: String::from("Higanbana"),
            snapshotted_buffs: Default::default(),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            damage_skill_id: Some(1119),
            potency: Some(50),
            trait_percent: Some(100),
            damage_category: Some(DamageCategory::PhysicalDot),
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 60000,
            is_raidwide: false,
            snapshotted_debuffs: Default::default(),
        };

        let OGI_NAMIKIRI_USED: BuffStatus = BuffStatus {
            id: 1106,
            name: String::from("Ogi Namikiri Used"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 3000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let ZANSHIN_READY: BuffStatus = BuffStatus {
            id: 1108,
            name: String::from("Zanshin Ready"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };

        let TENDO: BuffStatus = BuffStatus {
            id: 1109,
            name: String::from("Tendo"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };
        let MIDARE_USED: BuffStatus = BuffStatus {
            id: 1107,
            name: String::from("Midare Used"),
            stacks: 1,
            max_stacks: 1,
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            trigger_proc_event_on_gcd: vec![],
        };

        let GYOFU: AttackSkill = AttackSkill {
            id: 1100,
            name: String::from("Gyofu"),
            player_id,
            potency: 240,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(2),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: HashMap::from([(0, 5)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let JINPU: AttackSkill = AttackSkill {
            id: 1101,
            name: String::from("Jinpu"),
            player_id,
            potency: 300,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                FUGETSU.clone(),
                40000,
                40000,
                0,
            )],
            proc_events: vec![],
            combo: Some(3),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: HashMap::from([(0, 5)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let GEKKO: AttackSkill = AttackSkill {
            id: 1102,
            name: String::from("Gekko"),
            player_id,
            potency: 420,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(0),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: HashMap::from([(0, 10), (2, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::NoTarget,
        };
        let SHIFU: AttackSkill = AttackSkill {
            id: 1103,
            name: String::from("Shifu"),
            player_id,
            potency: 300,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                FUKA.clone(),
                40000,
                40000,
                0,
            )],
            proc_events: vec![],
            combo: Some(4),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: HashMap::from([(0, 5)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let KASHA: AttackSkill = AttackSkill {
            id: 1104,
            name: String::from("Kasha"),
            player_id,
            potency: 420,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(0),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: HashMap::from([(0, 10), (3, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let YUKIKAZE: AttackSkill = AttackSkill {
            id: 1105,
            name: String::from("Yukikaze"),
            player_id,
            potency: 340,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(0),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: HashMap::from([(0, 15), (4, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let HISSATSU_SHINTEN: AttackSkill = AttackSkill {
            id: 1106,
            name: String::from("Hissatsu: Shinten"),
            player_id,
            potency: 250,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::Resource(0, 25)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let HISSATSU_SENEI: AttackSkill = AttackSkill {
            id: 1107,
            name: String::from("Hissatsu: Senei"),
            player_id,
            potency: 860,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 60000,
            resource_required: vec![ResourceRequirements::Resource(0, 25)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let MEIKYO_SHISUI: AttackSkill = AttackSkill {
            id: 1108,
            name: String::from("Meikyo Shisui"),
            player_id,
            potency: 0,
            trait_percent: 100,
            additional_skill_events: vec![
                ApplyBuff(
                    player_id,
                    player_id,
                    MEIKYO_SHISUI_BUFF.clone(),
                    20000,
                    20000,
                    0,
                ),
                ApplyBuff(player_id, player_id, TENDO.clone(), 30000, 30000, 0),
            ],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 55000,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 2,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let KAESHI_TENDO_SETSUGEKKA: AttackSkill = AttackSkill {
            id: 1109,
            name: String::from("Kaeshi Tendo Setsugekka"),
            player_id,
            potency: 1020,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(TENDO_SETSUGEKKA_USED.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: true,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let GEKKO_MEIKYO: AttackSkill = AttackSkill {
            id: 1110,
            name: String::from("Gekko"),
            player_id,
            potency: 420,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                FUGETSU.clone(),
                40000,
                40000,
                0,
            )],
            proc_events: vec![],
            combo: Some(0),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(MEIKYO_SHISUI_BUFF.get_id())],
            resource_created: HashMap::from([(0, 10), (2, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let KASHA_MEIKYO: AttackSkill = AttackSkill {
            id: 1111,
            name: String::from("Kasha"),
            player_id,
            potency: 420,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                FUKA.clone(),
                40000,
                40000,
                0,
            )],
            proc_events: vec![],
            combo: Some(0),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(MEIKYO_SHISUI_BUFF.get_id())],
            resource_created: HashMap::from([(0, 10), (3, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let YUKI_MEIKYO: AttackSkill = AttackSkill {
            id: 1112,
            name: String::from("Yukikaze"),
            player_id,
            potency: 340,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(0),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 30000,
            resource_required: vec![UseBuff(MEIKYO_SHISUI_BUFF.get_id())],
            resource_created: HashMap::from([(0, 15), (4, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let IKISHOTEN: AttackSkill = AttackSkill {
            id: 1113,
            name: String::from("Ikishoten"),
            player_id,
            potency: 0,
            trait_percent: 100,
            additional_skill_events: vec![
                ApplyBuff(
                    player_id,
                    player_id,
                    OGI_NAMIKIRI_READY.clone(),
                    30000,
                    30000,
                    0,
                ),
                ApplyBuff(player_id, player_id, ZANSHIN_READY.clone(), 30000, 30000, 0),
            ],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 120000,
            resource_required: vec![],
            resource_created: HashMap::from([(0, 50)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let HAGAKURE: AttackSkill = AttackSkill {
            id: 1114,
            name: String::from("Hagakure"),
            player_id,
            potency: 0,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 10000,
            resource_required: vec![ResourceRequirements::Resource(4, 1)],
            resource_created: HashMap::from([(0, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let MIDARE_SETSUGEKKA: AttackSkill = AttackSkill {
            id: 1115,
            name: String::from("Midare Setsugekka"),
            player_id,
            potency: 700,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                MIDARE_USED.clone(),
                30000,
                30000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 1000,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![Resource(2, 1), Resource(3, 1), Resource(4, 1)],
            resource_created: HashMap::from([(1, 1)]),
            is_guaranteed_crit: true,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let OGI_NAMIKIRI: AttackSkill = AttackSkill {
            id: 1116,
            name: String::from("Ogi Namikiri"),
            player_id,
            potency: 900,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                OGI_NAMIKIRI_USED.clone(),
                3000,
                3000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 1000,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(OGI_NAMIKIRI_READY.get_id())],
            resource_created: HashMap::from([(1, 1)]),
            is_guaranteed_crit: true,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let KAESHI_NAMIKIRI: AttackSkill = AttackSkill {
            id: 1117,
            name: String::from("Kaeshi: Namikiri"),
            player_id,
            potency: 900,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(OGI_NAMIKIRI_USED.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: true,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let HIGANBANA_ONE: AttackSkill = AttackSkill {
            id: 1118,
            name: String::from("Higanbana"),
            player_id,
            potency: 200,
            trait_percent: 100,
            additional_skill_events: vec![ApplyDebuff(
                player_id,
                HIGANBANA_DOT.clone(),
                60000,
                60000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 1000,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![Resource(2, 1)],
            resource_created: HashMap::from([(1, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let HIGANBANA_TWO: AttackSkill = AttackSkill {
            id: 1119,
            name: String::from("Higanbana"),
            player_id,
            potency: 200,
            trait_percent: 100,
            additional_skill_events: vec![ApplyDebuff(
                player_id,
                HIGANBANA_DOT.clone(),
                60000,
                60000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 1000,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![Resource(3, 1)],
            resource_created: HashMap::from([(1, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let HIGANBANA_THREE: AttackSkill = AttackSkill {
            id: 1120,
            name: String::from("Higanbana"),
            player_id,
            potency: 200,
            trait_percent: 100,
            additional_skill_events: vec![ApplyDebuff(
                player_id,
                HIGANBANA_DOT.clone(),
                60000,
                60000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 1000,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![Resource(4, 1)],
            resource_created: HashMap::from([(1, 1)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let SHOHA: AttackSkill = AttackSkill {
            id: 1121,
            name: String::from("Shoha"),
            player_id,
            potency: 640,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![Resource(1, 3)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let ZANSHIN: AttackSkill = AttackSkill {
            id: 1122,
            name: String::from("Zanshin"),
            player_id,
            potency: 900,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![Resource(0, 50), UseBuff(ZANSHIN_READY.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let TENDO_SETSUGEKKA: AttackSkill = AttackSkill {
            id: 1123,
            name: String::from("Tendo Setsugekka"),
            player_id,
            potency: 1020,
            trait_percent: 100,
            additional_skill_events: vec![ApplyBuff(
                player_id,
                player_id,
                TENDO_SETSUGEKKA_USED.clone(),
                30000,
                30000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 1000,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![
                UseBuff(TENDO.id),
                Resource(2, 1),
                Resource(3, 1),
                Resource(4, 1),
            ],
            resource_created: HashMap::from([(1, 1)]),
            is_guaranteed_crit: true,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };
        let KAESHI_SETSUGEKKA: AttackSkill = AttackSkill {
            id: 1124,
            name: String::from("Kaeshi Setsugekka"),
            player_id,
            potency: 700,
            trait_percent: 100,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![UseBuff(MIDARE_USED.get_id())],
            resource_created: Default::default(),
            is_guaranteed_crit: true,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
            use_type: UseType::UseOnTarget,
        };

        let potion_skill = PotionSkill::new(player_id);

        SamuraiDatabase {
            gyofu: GYOFU,
            jinpu: JINPU,
            gekko: GEKKO,
            shifu: SHIFU,
            kasha: KASHA,
            yukikaze: YUKIKAZE,
            hissatsu_shinten: HISSATSU_SHINTEN,
            hissatsu_senei: HISSATSU_SENEI,
            meikyo_shisui: MEIKYO_SHISUI,
            gekko_meikyo: GEKKO_MEIKYO,
            kasha_meikyo: KASHA_MEIKYO,
            yuki_meikyo: YUKI_MEIKYO,
            ikishoten: IKISHOTEN,
            hagakure: HAGAKURE,
            kaeshi_tendo_setsugekka: KAESHI_TENDO_SETSUGEKKA,
            ogi_namikiri: OGI_NAMIKIRI,
            kaeshi_namikiri: KAESHI_NAMIKIRI,
            higanbana: HIGANBANA_ONE,
            midare_setsugekka: MIDARE_SETSUGEKKA,
            shoha: SHOHA,
            higanbana_two: HIGANBANA_TWO,
            higanbana_three: HIGANBANA_THREE,
            zanshin: ZANSHIN,
            tendo_setsugekka: TENDO_SETSUGEKKA,
            kaeshi_setsugekka: KAESHI_SETSUGEKKA,

            tendo_setsugekka_used: TENDO_SETSUGEKKA_USED,
            ogi_namikiri_ready: OGI_NAMIKIRI_READY,
            fugetsu: FUGETSU,
            fuka: FUKA,
            higanbana_dot: HIGANBANA_DOT,
            midare_used: MIDARE_USED,
            ogi_namikiri_used: OGI_NAMIKIRI_USED,
            meikyo_shisui_buff: MEIKYO_SHISUI_BUFF,

            zanshin_ready: ZANSHIN_READY,
            tendo: TENDO,
            potion: potion_skill.potion,
            potion_buff: potion_skill.potion_buff,
        }
    }
}

pub(crate) fn make_samurai_skill_list(player_id: PlayerIdType) -> SkillTable<AttackSkill> {
    let db = SamuraiDatabase::new(player_id);

    let samurai_skill_list: Vec<AttackSkill> = vec![
        db.gyofu,
        db.jinpu,
        db.gekko,
        db.shifu,
        db.kasha,
        db.yukikaze,
        db.hissatsu_shinten,
        db.hissatsu_senei,
        db.meikyo_shisui,
        db.gekko_meikyo,
        db.kasha_meikyo,
        db.yuki_meikyo,
        db.ikishoten,
        db.hagakure,
        db.kaeshi_tendo_setsugekka,
        db.ogi_namikiri,
        db.kaeshi_namikiri,
        db.higanbana,
        db.midare_setsugekka,
        db.shoha,
        db.higanbana_two,
        db.higanbana_three,
        db.zanshin,
        db.tendo_setsugekka,
        db.kaeshi_setsugekka,
        db.potion,
    ];

    make_skill_table(samurai_skill_list)
}
