# Etro Data File Paths
equipment_json_file_name: equipment_data.json
jobs_json_file_name: jobs_data.json
food_json_file_name: food_data.json
clans_json_file_name: clans_data.json

# Job Main/Sub Stat Constants
max_level_main_stat_modifier: 390.0
max_level_hp_modifier: 1900.0
max_level_div: 3000.0
hp_per_vitality_non_tank: 24.3
hp_per_vitality_tank: 34.6
max_level_base_vitality: 390
max_level_base_piety: 390
max_level_base_direct_hit: 400
max_level_base_critical_hit: 400
max_level_base_determination: 390
max_level_base_skill_speed: 400
max_level_base_spell_speed: 400
max_level_base_tenacity: 400