[package]
name = "ffxiv-simbot-cmd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ffxiv-simbot"
path = "src/main.rs"
doc = false

[dependencies.ffxiv-simbot-db]
version = "0.1.0"
path = "../lib/ffxiv-simbot-db"

[dependencies.ffxiv-simbot-engine]
version = "0.1.0"
path = "../lib/ffxiv-simbot-engine"

[dependencies.ffxiv-simbot-dps-simulator]
version = "0.1.0"
path = "../lib/ffxiv-simbot-dps-simulator"

[dependencies.ffxiv-simbot-combat-components]
version = "0.1.0"
path = "../lib/ffxiv-simbot-combat-components"
