pub(crate) struct FfxivConfig {
    max_level_main_stat_modifier: usize,
    max_level_hp_modifier: usize,
    max_level_mp_modifier: usize,
    max_level_critical_strike_base: usize,
    max_level_direct_hit_base: usize,
    max_level_determination_base: usize,
    max_level_tenacity_base: usize,
    max_level_skill_speed_base: usize,
    max_level_spell_speed_base: usize,
    pub(crate) equipment_json_file_name: String,
    pub(crate) jobs_json_file_name: String,
    pub(crate) food_json_file_name: String,
    pub(crate) materia_json_file_name: String,
    pub(crate) clans_json_file_name: String,
    pub(crate) medicine_json_file_name: String,
    pub(crate) job_json_file_name: String,
    pub(crate) clan_json_file_name: String,
}
