use crate::event::ffxiv_event::FfxivEvent;
use crate::rotation::SkillTable;
use crate::skill::attack_skill::AttackSkill;
use crate::skill::use_type::UseType;
use crate::skill::{make_skill_table, ResourceRequirements, ResourceTable};
use crate::status::buff_status::BuffStatus;
use crate::status::debuff_status::DebuffStatus;
use crate::status::status_info::StatusInfo;
use crate::IdType;

pub(crate) struct NinjaDatabase {
    pub(crate) huton: AttackSkill,
    pub(crate) raiton: AttackSkill,
    pub(crate) raiju: AttackSkill,
    pub(crate) hyosho: AttackSkill,
    pub(crate) suiton: AttackSkill,
    pub(crate) spinning_edge: AttackSkill,
    pub(crate) gust_slash: AttackSkill,
    pub(crate) aeolian_edge: AttackSkill,
    pub(crate) armor_crush: AttackSkill,
    pub(crate) mug: AttackSkill,
    pub(crate) trick_attack: AttackSkill,
    pub(crate) kassatsu: AttackSkill,
    pub(crate) bhavacakra: AttackSkill,
    pub(crate) tenchijin: AttackSkill,
    pub(crate) fuma_tenchijin: AttackSkill,
    pub(crate) raiton_tenchijin: AttackSkill,
    pub(crate) suiton_tenchijin: AttackSkill,
    pub(crate) bunshin: AttackSkill,
    pub(crate) dream: AttackSkill,
    pub(crate) phantom_kamaitachi: AttackSkill,
    pub(crate) meisui: AttackSkill,
    pub(crate) bhavacakra_meisui: AttackSkill,
    pub(crate) bunshin_stack: AttackSkill,
    pub(crate) mudra: AttackSkill,

    pub(crate) huton_status: BuffStatus,
    pub(crate) raijuready: BuffStatus,
    pub(crate) suiton_status: BuffStatus,
    pub(crate) mug_status: DebuffStatus,
    pub(crate) trick_attack_status: DebuffStatus,
    pub(crate) kassatsu_status: BuffStatus,
    pub(crate) tenchijin_status: BuffStatus,
    pub(crate) bunshin_status: BuffStatus,
    pub(crate) meisui_status: BuffStatus,
    pub(crate) bunshin_clone_status: BuffStatus,
}

impl NinjaDatabase {
    pub(crate) fn new(player_id: IdType) -> Self {
        let HUTON_STATUS: BuffStatus = {
            BuffStatus {
                id: 1000,
                name: String::from("Huton"),
                owner_id: player_id,
                duration_left_millisecond: 0,
                status_info: vec![StatusInfo::SpeedPercent(15)],
                duration_millisecond: 60000,
                is_raidwide: false,
                stacks: 1,
                max_stacks: 1,
                trigger_proc_event_on_gcd: vec![],
            }
        };
        let RAIJUREADY: BuffStatus = BuffStatus {
            id: 1001,
            name: String::from("Raiju Ready"),
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let SUITON_STATUS: BuffStatus = BuffStatus {
            id: 1002,
            name: String::from("Suiton"),
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 20000,
            is_raidwide: false,
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let MUG_STATUS: DebuffStatus = DebuffStatus {
            id: 1003,
            name: String::from("Mug"),
            owner_id: player_id,
            potency: None,
            damage_skill_id: None,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::DamagePercent(5)],
            duration_millisecond: 20000,
            is_raidwide: true,
            stacks: 1,
            snapshotted_buffs: Default::default(),
            snapshotted_debuffs: Default::default(),
            max_stacks: 1,
        };
        let TRICK_ATTACK_STATUS: DebuffStatus = DebuffStatus {
            id: 1004,
            name: String::from("Trick Attack"),
            owner_id: player_id,
            potency: None,
            damage_skill_id: None,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::DamagePercent(10)],
            duration_millisecond: 15000,
            is_raidwide: false,
            stacks: 1,
            snapshotted_buffs: Default::default(),
            snapshotted_debuffs: Default::default(),
            max_stacks: 1,
        };
        let KASSATSU_STATUS: BuffStatus = BuffStatus {
            id: 1005,
            name: String::from("Kassatsu"),
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 15000,
            is_raidwide: false,
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let TENCHIJIN_STATUS: BuffStatus = BuffStatus {
            id: 1006,
            name: String::from("Ten Chi Jin"),
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 6000,
            is_raidwide: false,
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let BUNSHIN_STATUS: BuffStatus = BuffStatus {
            id: 1007,
            name: String::from("Bunshin"),
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 45000,
            is_raidwide: false,
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let MEISUI_STATUS: BuffStatus = BuffStatus {
            id: 1008,
            name: String::from("Meisui"),
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };

        let TCJ_1: BuffStatus = BuffStatus {
            id: 1009,
            name: String::from("Ten Chi Jin-1"),
            owner_id: player_id,
            duration_left_millisecond: 6000,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 6000,
            is_raidwide: false,
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let TCJ_2: BuffStatus = BuffStatus {
            id: 1010,
            name: String::from("Ten Chi Jin-2"),
            owner_id: player_id,
            duration_left_millisecond: 6000,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 0,
            is_raidwide: false,
            stacks: 1,
            max_stacks: 1,
            trigger_proc_event_on_gcd: vec![],
        };
        let BUNSHIN_CLONE_STATUS: BuffStatus = BuffStatus {
            id: 1011,
            name: String::from("Bunshin Clone"),
            owner_id: player_id,
            duration_left_millisecond: 0,
            status_info: vec![StatusInfo::None],
            duration_millisecond: 30000,
            is_raidwide: false,
            stacks: 5,
            max_stacks: 5,
            trigger_proc_event_on_gcd: vec![],
        };
        let HUTON: AttackSkill = AttackSkill {
            id: 1000,
            name: String::from("Huton"),
            player_id,
            use_type: UseType::NoTarget,
            potency: 0,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                HUTON_STATUS.clone(),
                60000,
                60000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 1500,
            charging_time_millisecond: 1500,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
        };
        let RAITON: AttackSkill = AttackSkill {
            id: 1001,
            name: String::from("Raiton"),
            player_id,
            potency: 650,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuffStack(
                player_id,
                player_id,
                RAIJUREADY.clone(),
                30000,
                true,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 1500,
            charging_time_millisecond: 1000,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: Some(1023),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let RAIJU: AttackSkill = AttackSkill {
            id: 1002,
            name: String::from("Fleeting Raiju"),
            player_id,
            potency: 560,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::UseBuff(1001)],
            resource_created: ResourceTable::from([(0, 5)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
        };
        let HYOSHO: AttackSkill = AttackSkill {
            id: 1003,
            name: String::from("Hyosho Ranryu"),
            player_id,
            potency: 1300,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.3,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 1500,
            charging_time_millisecond: 1000,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::UseBuff(1005)],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let SUITON: AttackSkill = AttackSkill {
            id: 1004,
            name: String::from("Suiton"),
            player_id,
            potency: 500,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                SUITON_STATUS.clone(),
                20000,
                20000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 1500,
            charging_time_millisecond: 1500,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: Some(1023),
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let SPINNING_EDGE: AttackSkill = AttackSkill {
            id: 1005,
            name: String::from("Spinning Edge"),
            player_id,
            potency: 220,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(1),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: ResourceTable::from([(0, 5)]),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
        };
        let GUST_SLASH: AttackSkill = AttackSkill {
            id: 1006,
            name: String::from("Gust Slash"),
            player_id,
            potency: 320,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(2),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: ResourceTable::from([(0, 5)]),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let AEOLIAN_EDGE: AttackSkill = AttackSkill {
            id: 1007,
            name: String::from("Aeolian Edge"),
            player_id,
            potency: 440,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: Some(0),
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: ResourceTable::from([(0, 15)]),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let ARMOR_CRUSH: AttackSkill = AttackSkill {
            id: 1008,
            name: String::from("Armor Crush"),
            player_id,
            potency: 420,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                HUTON_STATUS.clone(),
                30000,
                60000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: true,
            cooldown_millisecond: 0,
            resource_required: vec![],
            resource_created: ResourceTable::from([(0, 15)]),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let MUG: AttackSkill = AttackSkill {
            id: 1009,
            name: String::from("Mug"),
            player_id,
            potency: 150,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyDebuff(
                player_id,
                MUG_STATUS.clone(),
                20000,
                20000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 120000,
            resource_required: vec![],
            resource_created: ResourceTable::from([(0, 40)]),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let TRICK_ATTACK: AttackSkill = AttackSkill {
            id: 1010,
            name: String::from("Trick Attack"),
            player_id,
            potency: 400,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyDebuff(
                player_id,
                TRICK_ATTACK_STATUS.clone(),
                15000,
                15000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 60000,
            resource_required: vec![ResourceRequirements::UseBuff(1002)],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let KASSATSU: AttackSkill = AttackSkill {
            id: 1011,
            name: String::from("Kassatsu"),
            player_id,
            potency: 0,
            use_type: UseType::NoTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                KASSATSU_STATUS.clone(),
                15000,
                15000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 60000,
            resource_required: vec![],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let BHAVACAKRA: AttackSkill = AttackSkill {
            id: 1012,
            name: String::from("Bhavakacra"),
            player_id,
            potency: 350,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::Resource(0, 50)],
            resource_created: Default::default(),
            is_guaranteed_crit: false,
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_direct_hit: false,
        };
        let TENCHIJIN: AttackSkill = AttackSkill {
            id: 1013,
            name: String::from("Ten Chi Jin"),
            player_id,
            potency: 0,
            use_type: UseType::NoTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                TENCHIJIN_STATUS.clone(),
                6000,
                6000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 120000,
            resource_required: vec![],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let FUMA_TENCHIJIN: AttackSkill = AttackSkill {
            id: 1014,
            name: String::from("Fuma Shuriken-TCJ"),
            player_id,
            potency: 450,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                TCJ_1.clone(),
                6000,
                6000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 1000,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::UseBuff(1006)],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let RAITON_TENCHIJIN: AttackSkill = AttackSkill {
            id: 1015,
            name: String::from("Raiton-TCJ"),
            player_id,
            potency: 560,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                TCJ_2.clone(),
                6000,
                6000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 1000,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::UseBuff(1009)],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let SUITON_TENCHIJIN: AttackSkill = AttackSkill {
            id: 1016,
            name: String::from("Suiton-TCJ"),
            player_id,
            potency: 500,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                SUITON_STATUS.clone(),
                20000,
                20000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 1000,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::UseBuff(1010)],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let BUNSHIN: AttackSkill = AttackSkill {
            id: 1017,
            name: String::from("Bunshin"),
            player_id,
            use_type: UseType::NoTarget,
            potency: 0,
            trait_multiplier: 1.0,
            additional_skill_events: vec![
                FfxivEvent::ApplyBuff(
                    player_id,
                    player_id,
                    BUNSHIN_STATUS.clone(),
                    45000,
                    45000,
                    0,
                ),
                FfxivEvent::ApplyBuff(
                    player_id,
                    player_id,
                    BUNSHIN_CLONE_STATUS.clone(),
                    30000,
                    30000,
                    0,
                ),
            ],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 90000,
            resource_required: vec![ResourceRequirements::Resource(0, 50)],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let DREAM: AttackSkill = AttackSkill {
            id: 1018,
            name: String::from("Dream Within a Dream"),
            player_id,
            potency: 450,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 60000,
            resource_required: vec![],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let PHANTOM_KAMAITACHI: AttackSkill = AttackSkill {
            id: 1019,
            name: String::from("Phantom Kamaitachi"),
            player_id,
            potency: 600,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 2500,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::UseBuff(1007)],
            resource_created: ResourceTable::from([(0, 10)]),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let MEISUI: AttackSkill = AttackSkill {
            id: 1020,
            name: String::from("Meisui"),
            player_id,
            potency: 0,
            use_type: UseType::NoTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![FfxivEvent::ApplyBuff(
                player_id,
                player_id,
                MEISUI_STATUS.clone(),
                30000,
                30000,
                0,
            )],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::UseBuff(1002)],
            resource_created: ResourceTable::from([(0, 50)]),
            current_cooldown_millisecond: 120000,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let BHAVACAKRA_MEISUI: AttackSkill = AttackSkill {
            id: 1021,
            name: String::from("Bhavakacra-Meisui"),
            player_id,
            potency: 500,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 1000,
            resource_required: vec![
                ResourceRequirements::Resource(0, 50),
                ResourceRequirements::UseBuff(1008),
            ],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let BUNSHIN_STACK: AttackSkill = AttackSkill {
            id: 1022,
            name: String::from("Bunshin-Stack"),
            player_id,
            potency: 150,
            use_type: UseType::UseOnTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 0,
            resource_required: vec![ResourceRequirements::UseBuff(BUNSHIN_CLONE_STATUS.id)],
            resource_created: ResourceTable::from([(0, 5)]),
            current_cooldown_millisecond: 0,
            stacks: 1,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };
        let MUDRA: AttackSkill = AttackSkill {
            id: 1023,
            name: String::from("Mudra"),
            player_id,
            potency: 0,
            use_type: UseType::NoTarget,
            trait_multiplier: 1.0,
            additional_skill_events: vec![],
            proc_events: vec![],
            combo: None,
            delay_millisecond: None,
            casting_time_millisecond: 0,
            gcd_cooldown_millisecond: 0,
            charging_time_millisecond: 0,
            is_speed_buffed: false,
            cooldown_millisecond: 20000,
            resource_required: vec![],
            resource_created: Default::default(),
            current_cooldown_millisecond: 0,
            stacks: 2,
            stack_skill_id: None,
            is_guaranteed_crit: false,
            is_guaranteed_direct_hit: false,
        };

        Self {
            huton: HUTON,
            raiton: RAITON,
            raiju: RAIJU,
            hyosho: HYOSHO,
            suiton: SUITON,
            spinning_edge: SPINNING_EDGE,
            gust_slash: GUST_SLASH,
            aeolian_edge: AEOLIAN_EDGE,
            armor_crush: ARMOR_CRUSH,
            mug: MUG,
            trick_attack: TRICK_ATTACK,
            kassatsu: KASSATSU,
            bhavacakra: BHAVACAKRA,
            tenchijin: TENCHIJIN,
            fuma_tenchijin: FUMA_TENCHIJIN,
            raiton_tenchijin: RAITON_TENCHIJIN,
            suiton_tenchijin: SUITON_TENCHIJIN,
            bunshin: BUNSHIN,
            dream: DREAM,
            phantom_kamaitachi: PHANTOM_KAMAITACHI,
            meisui: MEISUI,
            bhavacakra_meisui: BHAVACAKRA_MEISUI,
            bunshin_stack: BUNSHIN_STACK,
            mudra: MUDRA,
            huton_status: HUTON_STATUS,
            raijuready: RAIJUREADY,
            suiton_status: SUITON_STATUS,
            mug_status: MUG_STATUS,
            trick_attack_status: TRICK_ATTACK_STATUS,
            kassatsu_status: KASSATSU_STATUS,
            tenchijin_status: TENCHIJIN_STATUS,
            bunshin_status: BUNSHIN_STATUS,
            meisui_status: MEISUI_STATUS,
            bunshin_clone_status: BUNSHIN_CLONE_STATUS,
        }
    }
}

pub(crate) fn make_ninja_skill_list(player_id: IdType) -> SkillTable<AttackSkill> {
    let db = NinjaDatabase::new(player_id);

    let ninja_skill_list: Vec<AttackSkill> = vec![
        db.huton.clone(),
        db.raiton.clone(),
        db.raiju.clone(),
        db.hyosho.clone(),
        db.suiton.clone(),
        db.spinning_edge.clone(),
        db.gust_slash.clone(),
        db.aeolian_edge.clone(),
        db.armor_crush.clone(),
        db.mug.clone(),
        db.trick_attack.clone(),
        db.mug.clone(),
        db.kassatsu.clone(),
        db.bhavacakra.clone(),
        db.tenchijin.clone(),
        db.fuma_tenchijin.clone(),
        db.raiton_tenchijin.clone(),
        db.suiton_tenchijin.clone(),
        db.bunshin.clone(),
        db.dream.clone(),
        db.phantom_kamaitachi.clone(),
        db.meisui.clone(),
        db.bhavacakra_meisui.clone(),
        db.bunshin_stack.clone(),
        db.mudra.clone(),
    ];

    make_skill_table(ninja_skill_list)
}

#[inline]
pub(crate) fn bunshin_trigger_gcd_ids() -> Vec<IdType> {
    let db = NinjaDatabase::new(0);

    vec![
        db.aeolian_edge.id,
        db.gust_slash.id,
        db.spinning_edge.id,
        db.armor_crush.id,
        db.raiju.id,
    ]
}

#[inline]
pub fn bunshin_clone_id() -> IdType {
    let db = NinjaDatabase::new(0);

    db.bunshin_stack.id
}

#[inline]
pub(crate) fn bunshin_stack_id() -> IdType {
    let db = NinjaDatabase::new(0);
    db.bunshin_clone_status.id
}

pub(crate) fn get_huton_status(player_id: IdType) -> BuffStatus {
    let db = NinjaDatabase::new(0);
    let mut huton = db.huton_status.clone();
    huton.owner_id = player_id;
    huton.duration_left_millisecond = 55000;

    huton
}
